imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true


services:
    user_service:
        class: Backend\UserBundle\Services\UserService
        arguments: ["@doctrine.orm.entity_manager"]
    cuit_unique_validator:
        class: Backend\AdminBundle\Validator\Constraints\CuitUniqueValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: cuit_unique                
    dni_unique_validator:
        class: Backend\AdminBundle\Validator\Constraints\DniUniqueValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: dni_unique
    code_unique_validator:
        class: Backend\AdminBundle\Validator\Constraints\CodeUniqueValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: code_unique
    usuario_unique_validator:
        class: Backend\UserBundle\Validator\Constraints\UsuarioUniqueValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: usuario_unique     
    email_unique_validator:
        class: Backend\UserBundle\Validator\Constraints\EmailUniqueValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: email_unique  
     
parameters:
    max_on_listepage: 20
    role_default: ROLE_VISITOR # este es asignado por default a quien se registra
    role_admin: ROLE_ADMIN  #este debe existir y no puede borrarse 
    role_deposito: ROLE_DEPOSITO #este es el que se controla para manejar los depositos
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig    
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

         