backend_admin_homepage:
    pattern:  /
    defaults: { _controller: BackendAdminBundle:Default:index }

blank:
    pattern:  /blank
    defaults: { _controller: BackendAdminBundle:Default:blank }

backend_cliente:
    resource: "@BackendAdminBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente    

backend_sucursal:
    resource: "@BackendAdminBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal