backend_admin_homepage:
    pattern:  /
    defaults: { _controller: BackendAdminBundle:Default:index }

blank:
    pattern:  /blank
    defaults: { _controller: BackendAdminBundle:Default:blank }

backend_cliente:
    resource: "@BackendAdminBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente    

backend_marca:
    resource: "@BackendAdminBundle/Resources/config/routing/marca.yml"
    prefix:   /marca    

backend_provincia:
    resource: "@BackendAdminBundle/Resources/config/routing/provincia.yml"
    prefix:   /provincia
    
backend_zona:
    resource: "@BackendAdminBundle/Resources/config/routing/zona.yml"
    prefix:   /zona    

backend_modelo:
    resource: "@BackendAdminBundle/Resources/config/routing/modelo.yml"
    prefix:   /modelo    

backend_sintoma:
    resource: "@BackendAdminBundle/Resources/config/routing/sintoma.yml"
    prefix:   /sintoma    

backend_sucursal:
    resource: "@BackendAdminBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal
    
backend_area_trabajo:
    resource: "@BackendAdminBundle/Resources/config/routing/areaTrabajo.yml"
    prefix:   /areaTrabajo
    
backend_tipo_deposito:
    resource: "@BackendAdminBundle/Resources/config/routing/tipoDeposito.yml"
    prefix:   /tipoDeposito
    
backend_tipo_articulo:
    resource: "@BackendAdminBundle/Resources/config/routing/tipo_articulo.yml"
    prefix:   /tipo_articulo

backend_articulo:
    resource: "@BackendAdminBundle/Resources/config/routing/articulo.yml"
    prefix:   /articulo        
    
