backend_admin_homepage:
    pattern:  /
    defaults: { _controller: BackendAdminBundle:Default:index }

blank:
    pattern:  /blank
    defaults: { _controller: BackendAdminBundle:Default:blank }

backend_cliente:
    resource: "@BackendAdminBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente    

backend_sucursal:
    resource: "@BackendAdminBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal
    
backend_area_trabajo:
    resource: "@BackendAdminBundle/Resources/config/routing/areaTrabajo.yml"
    prefix:   /areaTrabajo
    
backend_tipo_deposito:
    resource: "@BackendAdminBundle/Resources/config/routing/tipoDeposito.yml"
    prefix:   /tipoDeposito
    
    
