Backend\AdminBundle\Entity\Cliente:
    properties:
        name:
            - NotBlank: { message: Olvido ingresar el Nombre / Razón Social }
            - Length: 
                min: 2
                max: 100
                minMessage: "El nombre debe tener al menos 2 carácteres"
                maxMessage: "El nombre debe tener 100 carácteres máximo"
        direccion:  
            - NotBlank: { message: Olvido ingresar la dirección }
            - Length: 
                min: 2
                max: 100
                minMessage: "La dirección debe tener al menos 2 carácteres"
                maxMessage: "La dirección puede tener 100 carácteres máximo"
        observacion: 
            - Length: 
                max: 500
                maxMessage: "La observación puede tener 500 carácteres máximo"  
        email:
            - Email: { message: Ingrese un email válido } 
