parameters:
#    itwb_user.example.class: ITWB\UserBundle\Example

services:
#    itwb_user.example:
#        class: %itwb_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
