caja_empleado:
    pattern:  /
    defaults: { _controller: "BackendAdminBundle:Caja:index" }

caja_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendAdminBundle:Caja:show" }

caja_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Caja:new" }

caja_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Caja:create" }
    requirements: { _method: post }

caja_newpopup:
    pattern:  /newpopup/{id}
    defaults: { _controller: "BackendAdminBundle:Caja:newPopup" }

caja_createpopup:
    pattern:  /createpopup
    defaults: { _controller: "BackendAdminBundle:Caja:createPopup" }
    requirements: { _method: post }
    
caja_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Caja:edit" }

caja_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Caja:update" }
    requirements: { _method: post|put }

caja_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Caja:delete" }
    requirements: { _method: post|delete }

caja_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Caja:exportar" }

caja_descontar:
    pattern:  /descontar
    defaults: { _controller: "BackendAdminBundle:Caja:descontar" }


    