chofer_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Chofer:new" }

chofer_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Chofer:exportar" }

chofer_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Chofer:create" }
    requirements: { _method: post }

chofer_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Chofer:edit" }

chofer_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Chofer:update" }
    requirements: { _method: post|put }

chofer_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Chofer:delete" }
    requirements: { _method: post|delete }
chofer:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Chofer:index" , search: ''}
