empresa_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Empresa:new" }

empresa_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Empresa:exportar" }

empresa_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Empresa:create" }
    requirements: { _method: post }

empresa_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Empresa:edit" }

empresa_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Empresa:update" }
    requirements: { _method: post|put }

empresa_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Empresa:delete" }
    requirements: { _method: post|delete }
empresa:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Empresa:index" , search: ''}
