sucursal_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:Sucursal:new" }

sucursal_exportar:
    pattern:  /exportar
    defaults: { _controller: "BackendAdminBundle:Sucursal:exportar" }
    
sucursal_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:Sucursal:create" }
    requirements: { _method: post }

sucursal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:Sucursal:edit" }

sucursal_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:Sucursal:update" }
    requirements: { _method: post|put }

sucursal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:Sucursal:delete" }
    requirements: { _method: post|delete }

sucursal:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:Sucursal:index" , search: ''}
