
tipomovimiento_new:
    pattern:  /new
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:new" }

tipomovimiento_create:
    pattern:  /create
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:create" }
    requirements: { _method: post }

tipomovimiento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:edit" }

tipomovimiento_update:
    pattern:  /{id}/update
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:update" }
    requirements: { _method: post|put }

tipomovimiento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:delete" }
    requirements: { _method: post|delete }

tipomovimiento:
    pattern:  /{search}
    defaults: { _controller: "BackendAdminBundle:TipoMovimiento:index",  search: '' }
